### ISSUE TITLE
make this into a gist instead of repo since isnt very useful

### ISSUE THREAD

**Issue by ysIgnacio** [1x6/cloudflare-bulk-delete#3]
!!!

**Comment by ysIgnacio** [comment]
@1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6 @1x6

**Comment by ysIgnacio** [comment]
oh wait since when im contributor

**Comment by 1x6** [comment]
nahhhh idc lol.

**Comment by ysIgnacio** [comment]
> nahhhh idc lol.

die
